version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:80
      - 9229:9229
    env_file:
      - .env

  # redis:
  #   container_name: redis
  #   image: redis:5

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data