apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-background
  labels:
    service: {{ .Chart.Name }}-background
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-background
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}-background
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: default

      containers:
      - name: {{ .Chart.Name }}-background
        image: {{ .Values.werf.image.backend }}

        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP

        env:
        - name: NO_BACKGROUND
          value: "false"

        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-env
            
      imagePullSecrets:
      - name: {{ .Chart.Name }}-pullsecret

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-background-svc
spec:
  selector:
    service: {{ .Chart.Name }}-background
  clusterIP: None
  ports:
  - port: 8000